### ISSUE TITLE
Improved input of output signals

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Sharparam/cybersyn-combinator#22]
### Description

I want to suggest, if possible, to make changes in the behavior of the combinator. Namely, in terms of introducing digital values of output signals.

### Context

Since negative values of the signals must be suppressed for the operation of the request station, I suggest that after entering a positive number of stacks or the number of objects into the combinator interface, it becomes negative.

If there are situations in which these values should be positive, please tell us about them because I could not find such situations on my own

### Implementation

https://github.com/kryojenik/LTN_Combinator_Modernized/issues/21

**Comment by Sharparam** [comment]
Added an option in v0.5.0 to convert all items and fluids to negative signals (virtual signals are left untouched).

I set the default as off, so that existing installs don't change behaviour (which is different from LTN combinator that sets the default as on).

**Comment by Sharparam** [comment]
Apparently managed to tag the wrong commit because of a miss while rebasing, so if you already downloaded 0.5.0, download it again >.>
