### ISSUE TITLE
Improving the informativeness of the combinator interface

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Sharparam/cybersyn-combinator#23]
### Description

It would be convenient if there was an indicator in the interface that shows the total number of packs of goods that were ordered in the "output signals" section

### Context

Since the essence of the cybersyn mod is that trains automatically maintain the number of ordered goods in order to avoid station overflow, it is impossible to order more packs than the receiving warehouse can accommodate

**Comment by Sharparam** [comment]
I'm not sure I'm following completely. Is it about being able to see if the total count of items requested would be larger than the total storage at the station can hold? The combinator does not have any information about how much storage is built at the station.

Or is it just showing a number that is the sum of all request counts? That should be pretty simple to add if so.

**Comment by Eldrinn-Elantey** [comment]
Just a counter of the total order in bundles (you can also in items, just in case) and the player will already compare with the station 's chests

**Comment by Sharparam** [comment]
With bundles, that means stack counts?

**Comment by Eldrinn-Elantey** [comment]
Yes that's right

**Comment by Eldrinn-Elantey** [comment]
Hi, how are things going with this idea?

**Comment by Eldrinn-Elantey** [comment]
Do you mean the names "Items" Item stacks" "Fluids"?

**Comment by Eldrinn-Elantey** [comment]
I am not a native English speaker to suggest suitable options. One way or another I will translate into my own language

**Comment by Eldrinn-Elantey** [comment]
![image](https://github.com/Sharparam/cybersyn-combinator/assets/46845681/a6bd1891-0a5a-41f6-a906-a7f9a9415e5b)


I set myself this version and noticed the first bug, so to speak. For the dispatcher to work, we specify values with a minute sign. Total, respectively, is also obtained with a minus

**Comment by Sharparam** [comment]
Oh of course. I suppose it should collect only negative signals and show the absolute value of those instead. Nice catch!

(There's also that question about whether signals should simply be input positive in this combinator, and they are then converted to negative values behind the scenes, but that is a topic for a separate issue.)

**Comment by Sharparam** [comment]
The latest build artifact now has fixed logic for counting the totals: https://github.com/Sharparam/cybersyn-combinator/suites/14838947884/artifacts/844953705

I also added tooltips to the labels which explains them.

Included in this is also a more explicit name for the combinator ("Cybersyn Constant Combinator") to help avoid confusion with the combinator from Project Cybersyn itself ("Cybernetic combinator"), just so you're aware.

Also, if you're able, if you can translate the new locale strings to Russian then that can also be included for the 0.6.0 update :)

**Comment by Eldrinn-Elantey** [comment]
[mod.zip](https://github.com/Sharparam/cybersyn-combinator/files/12266779/mod.zip)
![image](https://github.com/Sharparam/cybersyn-combinator/assets/46845681/4fd666c1-e69c-4019-bea6-6cda8ab211b8)

**Comment by Sharparam** [comment]
And now it's live in v0.6.0! Thanks for the testing and translation ^^
