### ISSUE TITLE
Strange interface behavior

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Sharparam/cybersyn-combinator#30]
After the last update, I noticed one oddity when editing a query, you can select all cells with a signal

![image](https://github.com/Sharparam/cybersyn-combinator/assets/46845681/9a22e1ff-7a97-4e6b-88b8-2b1c5266783a)

**Comment by Sharparam** [comment]
I noticed a similar issue if I click to edit a different cell before I've finished editing the current. Is that the same method to reproduce the issue for you?

**Comment by Eldrinn-Elantey** [comment]
Right. I started editing one cell, realized that I had made a mistake and switched the LMB to another and noticed that both were burning with a selection. I repeated this until everyone caught fire.

**Comment by Sharparam** [comment]
Indeed. It should be a pretty simple fix at least!

**Comment by Sharparam** [comment]
And now v0.6.1 is out on the mod portal with the fix.

Thanks for reporting!
