### ISSUE TITLE
Discord invite link broken

### ISSUE THREAD

**Issue by xaviershay** [Sharparam/cybersyn-combinator#34]
### Description

Discord invite link in README + mod page is broken.

### Expected behaviour

It should go to a valid invite :)

### Actual behaviour

It doesn't.

### Steps to reproduce

Click the link

### Context

Looking for some help debugging. (But cut+paste station fixed which was very unsatisfying but got me going for now.)

### Possible fix

Is the discord still active?

### Mod version

1.1

### Factorio version

1.1.76

### Operating system

Windows

**Comment by xaviershay** [comment]
ps thank you for this mod I love it

**Comment by Sharparam** [comment]
There are no links to the Cybersyn discord on either the mod page or the README. Where are you looking?

**Comment by Sharparam** [comment]
Closing due to lack of information, feel free to comment/re-open if still relevant.
