### ISSUE TITLE
Support for copy-pasting signals

### ISSUE THREAD

**Issue by yangsuo1991** [Sharparam/cybersyn-combinator#35]
### Description

Adding support for copy-pasting signals from assembler recipes

### Context

I'm absolutely enjoying Cybersyn and this mod! Without them I simply cannot continue my Py run.
I was wondering if you are planning to implement copy-pasting signals from assemblers? It's supported in LTN combinator via a [mod](https://mods.factorio.com/mod/copy-paste-recipe-signals-to-combinator) and it helped me a ton. 
Thanks again!

**Comment by Sharparam** [comment]
So I did some testing and made some progress. It looks like this is possible to implement with some hacky ways to listen for the entity settings being pasted from an assembler (the event for settings paste only works between constant combinators, some custom input event listening is required to support assembling machines).

What remains is determining the behaviour on paste.

For requester chests, all the contents are always overwritten with the recipe, even if previous logistic requests were already set. And if there's no recipe set in the assembling machine being copied, all the request signals are cleared.

Would that be the desired result for the Cybersyn Constant Combinator as well?

**Comment by Sharparam** [comment]
Ok I have code for this that works on the `main` branch now, should be ready for release but I'll get some more testing in first.

**Comment by Sharparam** [comment]
Forgot to update this issue, but this was added some versions ago.
