### ISSUE TITLE
Ghost combinator uses wrong (constant combinator) GUI

### ISSUE THREAD

**Issue by AllenJB** [Sharparam/cybersyn-combinator#39]
### Description

When attempting to modify combinator settings of a ghost combinator (in remote view), the wrong GUI is presented.

### Expected behaviour

Same GUI as a non-ghost combinator appears.

### Actual behaviour

Standard constant combinator GUI appears.

### Steps to reproduce

1. Create a station that uses the combinator
2. Copy and paste station (including combinator) to new location
3. Attempt to modify ghost combinator settings

(Steps 2 & 3 were performed in remote view, but I doubt that matters)

### Mod version

2.1.2

### Factorio version

2.0.10

### Operating system

Windows 11

**Comment by Sharparam** [comment]
Fixed in v2.1.3 (https://github.com/Sharparam/cybersyn-combinator/commit/66d44f6d325320c3fb4b41fd45cb4048181664d0) (forgot to tag the issue in the commit).

Thanks for reporting!
