### ISSUE TITLE
Bug: Selecting Output signal of existing output results in crash

### ISSUE THREAD

**Issue by pmsharp2** [Sharparam/cybersyn-combinator#41]
### Description

Selecting a duplicate signal out results in the following crash: 
`The mod Cybersyn Combinator (2.1.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event cybersyn-combinator::on_gui_elem_changed (ID 76)
Filter conflicts with filter in slot 1.
stack traceback:
	[C]: in function 'set_slot'
	__cybersyn-combinator__/scripts/combinator.lua:285: in function 'set_slot'
	__cybersyn-combinator__/scripts/combinator.lua:183: in function 'set_item_slot'
	__cybersyn-combinator__/scripts/gui.lua:473: in function 'handler'
	__flib__/gui.lua:177: in function <__flib__/gui.lua:160>`

### Expected behaviour

Selecting an existing output should do nothing.

### Actual behaviour

mod crashes exiting to the main menu

### Steps to reproduce

Create a combinator. 
in signal output slot 1 select iron
in signal output of slot 2 select iron
crash

### Context

Users error made me discover this no actual impact

### Mod version

2.0.2

### Factorio version

2.0.12

### Operating system

Windows 10 x64

**Comment by Sharparam** [comment]
I guess this is something that changed with 2.0 combinators, it used to be you could have duplicate signals and it would just be added together in the output.

I'll have to add some code to check for this and prevent duplicate inputs, nice catch!

**Comment by Sharparam** [comment]
v2.1.4 will be on the mod portal shortly with a fix for this!
